add ip check step

diff --git a/.github/workflows/BuildTestDeploy.yaml b/.github/workflows/BuildTestDeploy.yaml
--- a/.github/workflows/BuildTestDeploy.yaml
+++ b/.github/workflows/BuildTestDeploy.yaml
@@ -69,7 +69,7 @@ jobs:
     # needs: build-and-test
     runs-on: ubuntu-latest
     outputs:
-      ec2_public_ip: ${{ steps.capture-outputs.outputs.ec2_public_ip }}
+      ec2_public_ip: ${{ steps.capture-ip.outputs.ec2_public_ip }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -93,12 +93,12 @@ jobs:
       - name: Terraform Apply
         run: terraform apply -auto-approve
         working-directory: envs/dev
-      - id: capture-outputs
+      - id: capture-ip
         name: Capture EC2 public IP output
         run: |
           terraform output -raw instance_public_ip
-          ec2_public_ip=$(terraform output -raw instance_public_ip | head -n 1)
-          echo "ec2_public_ip=$ec2_public_ip" >> "$GITHUB_OUTPUT"
+          ip=$(terraform output -raw instance_public_ip | head -n 1)
+          echo "ec2_public_ip=$ip" >> "$GITHUB_OUTPUT"
         working-directory: envs/dev
   deploy-code:
     environment: "AWS and Supabase"
@@ -116,12 +116,20 @@ jobs:
       - name: Set up SSH key
         run: |
             mkdir -p ~/.ssh
-            echo "${{ secrets.EC2_SSH_PUBLIC_KEY }}" > ~/.ssh/my_ec2_key
+            echo $SSH_PRIVATE_KEY > ~/.ssh/my_ec2_key
             chmod 600 ~/.ssh/my_ec2_key
             echo "SSH key set up successfully"
       - name: SSH into EC2 instance
         run: |
+          # Check if the IP address was passed correctly
+            if [ -z "$EC2_PUBLIC_IP" ] || ! echo "$EC2_PUBLIC_IP" | grep -Eq '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'; then
+            echo "Error: EC2 Public IP is not set."
+            exit 1
+          fi
+
           ssh -o StrictHostKeyChecking=no -i ~/.ssh/my_ec2_key ec2-user@"$EC2_PUBLIC_IP" << 'EOF'
+      - name: Deploy image with dockerhub
+        run: |
           docker compose -f compose.yaml up -d --no-build
           docker ps
           EOF
